# Generated by Django 5.2.5 on 2025-08-31 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_alunoprofile_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='projIntegrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tema', models.CharField(max_length=200)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.professorprofile')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.turma')),
            ],
        ),
    ]
