# Generated by Django 5.2.2 on 2025-09-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projIntegrador', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projintegrador',
            old_name='professor',
            new_name='professor_id',
        ),
        migrations.RenameField(
            model_name='projintegrador',
            old_name='Tema',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='projintegrador',
            old_name='turma',
            new_name='turma_id',
        ),
        migrations.AddField(
            model_name='projintegrador',
            name='descricao',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
