# Generated by Django 5.2.2 on 2025-09-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projIntegrador', '0003_rename_professor_projintegrador_professor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projintegrador',
            old_name='professor_id',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='projintegrador',
            old_name='turma_id',
            new_name='turma',
        ),
    ]
