# Generated by Django 5.2.5 on 2025-08-30 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeGrupo', models.CharField(max_length=120)),
                ('DataCriacao', models.DateTimeField(auto_now_add=True)),
                ('integrantes', models.ManyToManyField(limit_choices_to={'role': 'ALUNO'}, related_name='grupos', to=settings.AUTH_USER_MODEL)),
                ('lider', models.ForeignKey(blank=True, limit_choices_to={'role': 'ALUNO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lideranca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
