# Generated by Django 5.2.5 on 2025-09-07 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo', '0001_initial'),
        ('projIntegrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='ProjetoIntegrador',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjetoIntegrador', to='projIntegrador.projintegrador'),
        ),
    ]
