# Generated by Django 5.2.5 on 2025-09-07 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='lider',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ALUNO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lideranca', to=settings.AUTH_USER_MODEL),
        ),
    ]
