# Generated by Django 5.2.2 on 2025-09-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='DataCriacao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='lider',
            new_name='lider_id',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='NomeGrupo',
            new_name='nome_grupo',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='ProjetoIntegrador',
            new_name='projeto_integrador_id',
        ),
    ]
