# Generated by Django 5.2.5 on 2025-09-19 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0004_rename_datacriacao_grupo_data_criacao_and_more'),
        ('usuarios', '0008_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='lider_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lideranca', to='usuarios.alunoprofile'),
        ),
    ]
