# Generated by Django 5.2.2 on 2025-09-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0005_alter_grupo_lider_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='lider_id',
            new_name='lider',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='projeto_integrador_id',
            new_name='projeto_integrador',
        ),
    ]
