# Generated by Django 5.2.5 on 2025-09-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0006_rename_lider_id_grupo_lider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/images'),
        ),
    ]
