# Generated by Django 5.2.5 on 2025-10-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0007_grupo_image'),
        ('projIntegrador', '0004_rename_professor_id_projintegrador_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='projeto_integrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjetoIntegrador', to='projIntegrador.projintegrador'),
        ),
    ]
