# Generated by Django 5.2.5 on 2025-10-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0008_alter_grupo_projeto_integrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
