# Generated by Django 5.2.5 on 2025-11-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0009_alter_grupo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='objetivo_projeto',
            field=models.TextField(default='Escreva aqui uma breve descricao de qual é o objetivo do projeto criado.'),
            preserve_default=False,
        ),
    ]
