# Generated by Django 5.2.2 on 2025-09-16 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0004_rename_datacriacao_grupo_data_criacao_and_more'),
        ('tarefa', '0001_initial'),
        ('usuarios', '0007_rename_grupo_alunoprofile_grupo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statustarefa',
            old_name='nomeStatus',
            new_name='nome_status',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='dataCriacao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='statusTarefa',
            new_name='status_tarefa_id',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='aluno_profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.alunoprofile'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='grupo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo.grupo'),
        ),
    ]
