# Generated by Django 5.2.2 on 2025-09-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_rename_nomestatus_statustarefa_nome_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='aluno_profile_id',
            new_name='aluno_profile',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='grupo_id',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='status_tarefa_id',
            new_name='status_tarefa',
        ),
    ]
