# Generated by Django 5.2.5 on 2025-09-07 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0001_initial'),
        ('projIntegrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ProjIntegrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projIntegrador.projintegrador'),
        ),
        migrations.AddField(
            model_name='evento',
            name='statusEvento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento.statusevento'),
        ),
    ]
