# Generated by Django 5.2.2 on 2025-09-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='dataCriacao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='ProjIntegrador',
            new_name='projeto_integrador_id',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='statusEvento',
            new_name='status_evento_id',
        ),
        migrations.RenameField(
            model_name='statusevento',
            old_name='NomeStatusEvento',
            new_name='nome_status',
        ),
    ]
