# Generated by Django 5.2.2 on 2025-09-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_rename_datacriacao_evento_data_criacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='projeto_integrador_id',
            new_name='projeto_integrador',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='status_evento_id',
            new_name='status_evento',
        ),
    ]
