# Generated by Django 5.2.5 on 2025-10-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_rename_projeto_integrador_id_evento_projeto_integrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='projeto_integrador',
        ),
    ]
