# Generated by Django 5.2.5 on 2025-11-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_remove_evento_projeto_integrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
