# Generated by Django 5.2.5 on 2025-11-12 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0005_remove_evento_projeto_integrador'),
        ('grupo', '0009_alter_grupo_image'),
        ('tarefa', '0003_rename_aluno_profile_id_tarefa_aluno_profile_and_more'),
        ('usuarios', '0010_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento_alterado', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('evento_alterada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.evento')),
                ('grupo_alterado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo.grupo')),
                ('tarefa_alterada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarefa.tarefa')),
                ('usuario_alterador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.alunoprofile')),
                ('tipo_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='historico.tipoalteracao')),
            ],
        ),
    ]
