# Generated by Django 5.2.5 on 2025-11-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoalteracao',
            name='descricao',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
