# Generated by Django 5.2.5 on 2025-11-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0002_tipoalteracao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoalteracao',
            name='descricao',
            field=models.CharField(max_length=300),
        ),
    ]
