# Generated by Django 5.2.5 on 2025-09-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma', to='usuarios.turma'),
        ),
        migrations.AlterField(
            model_name='alunoprofile',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AlunoProfileturma', to='usuarios.turma'),
        ),
    ]
