# Generated by Django 5.2.5 on 2025-09-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_turma_alter_alunoprofile_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.turma'),
        ),
    ]
