# Generated by Django 5.2.5 on 2025-08-30 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0001_initial'),
        ('usuarios', '0002_turma_professorprofile_alunoprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunoprofile',
            name='turma',
        ),
        migrations.AddField(
            model_name='alunoprofile',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='grupo.grupo'),
        ),
    ]
