# Generated by Django 5.2.5 on 2025-08-30 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0001_initial'),
        ('usuarios', '0003_remove_alunoprofile_turma_alunoprofile_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoprofile',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='grupo.grupo'),
        ),
    ]
