# Generated by Django 5.2.5 on 2025-09-07 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoprofile',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_profile_turma', to='usuarios.turma'),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
