# Generated by Django 5.2.2 on 2025-09-12 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0003_initial'),
        ('usuarios', '0005_remove_user_last_name_alter_alunoprofile_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoprofile',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='grupo.grupo'),
        ),
        migrations.AlterField(
            model_name='alunoprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
