# Generated by Django 5.2.2 on 2025-09-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_alunoprofile_grupo_alter_alunoprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunoprofile',
            old_name='grupo',
            new_name='grupo_id',
        ),
        migrations.RenameField(
            model_name='alunoprofile',
            old_name='turma',
            new_name='turma_id',
        ),
        migrations.RenameField(
            model_name='alunoprofile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='professorprofile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='NomeTurma',
            new_name='nome_turma',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='turma',
            new_name='turma_id',
        ),
    ]
