# Generated by Django 5.2.2 on 2025-09-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunoprofile',
            old_name='grupo_id',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='alunoprofile',
            old_name='turma_id',
            new_name='turma',
        ),
        migrations.RenameField(
            model_name='alunoprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='professorprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='turma_id',
            new_name='turma',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
